services:

  db:
    image: postgres:18
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql
      - postgres_logs:/var/log/postgresql
      - ./tools/postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable"
    depends_on:
      - db

  backend:
    build:
      context: ./backend
    container_name: asset-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    volumes:
      - backend_logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
      alloy:
        condition: service_started
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:8081/actuator/health | grep -q '\"status\":\"UP\"'" ]
      interval: 15s # check every 15s
      timeout: 5s # fail if no response in 5s
      retries: 5 # mark unhealthy after 5 consecutive failures
      start_period: 120s # give Spring Boot 60s to start before counting failures

  frontend:
    build:
      context: ./frontend
    container_name: asset-frontend
    restart: unless-stopped
    ports:
      - "3000:8080"
    depends_on:
      backend:
        condition: service_started
    healthcheck:
      test: [ "CMD-SHELL", "curl -sf http://localhost:8080/ > /dev/null || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s

  prometheus:
    image: prom/prometheus:main-busybox
    container_name: prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-remote-write-receiver'
    volumes:
      - ./tools/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    command:
      - run
      - /etc/alloy/config.alloy
    volumes:
      - ./tools/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - postgres_logs:/var/log/postgresql:ro
      - backend_logs:/var/log/backend:ro
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - loki
      - tempo
      - prometheus

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: [ "-config.file=/etc/loki/config.yaml" ]
    volumes:
      - ./tools/loki/config.yaml:/etc/loki/config.yaml:ro
      - loki_data:/loki
    ports:
      - "3100:3100"

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo/config.yaml" ]
    volumes:
      - ./tools/tempo/config.yaml:/etc/tempo/config.yaml:ro
      - tempo_data:/var/tempo
    ports:
      - "3200:3200"
    expose:
      - "4317"
      - "4318"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - grafana_data:/var/lib/grafana
      - ./tools/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "4000:3000"
    depends_on:
      - prometheus
      - loki
  # FOR LOCAL DEVELOPMENT ONLY
  # alloy:
  #   image: 'grafana/otel-lgtm:latest'
  #   ports:
  #     - '4000:3000'
  #     - '4317:4317'
  #     - '4318:4318'

volumes:
  db_data:
  prometheus_data:
  grafana_data:
  loki_data:
  tempo_data:
  postgres_logs:
  backend_logs:
