services:

  backend:
    environment:
      SPRING_PROFILES_ACTIVE: dev
    develop:
      watch:
        - action: rebuild
          path: ./backend/src
        - action: rebuild
          path: ./backend/pom.xml

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    env_file:
      - ./frontend/.env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    develop:
      watch:
        - action: rebuild
          path: ./frontend/src
        - action: rebuild
          path: ./frontend/public
        - action: rebuild
          path: ./frontend/package.json
    depends_on:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:5173 > /dev/null 2>&1 || exit 1" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
